categoryServiceJSP
StanislawGlegola/dev-shop pull request #13
Opened 2019-09-07 18:30 UTC by StanislawGlegola

2019-09-07 19:14 UTC, matacz83 commented on src/main/java/com/devshop/devshop/controller/AppController.java
> +    @GetMapping("/home")
@GetMapping("/")

2019-09-07 19:15 UTC, matacz83 commented on src/main/java/com/devshop/devshop/controller/AppController.java
> +    @GetMapping("/home")
@GetMapping("/")

2019-09-07 19:19 UTC, matacz83 commented on src/main/java/com/devshop/devshop/controller/AppController.java
> +        modelAndView.addObject("category_name", categories);
a nie "categoryName" ?

2019-09-07 19:26 UTC, matacz83 commented on src/main/java/com/devshop/devshop/controller/AppController.java
> +    @GetMapping("/home")
@GetMapping("/")

2019-09-08 07:18 UTC, CKochanski requested changes

2019-09-08 07:18 UTC, CKochanski commented on src/main/resources/data.sql
> +insert INTO Category(id, category_name) values (nextval('product_seq'),'Laptopy');
product_seq dla kategorii?

2019-09-08 07:18 UTC, CKochanski commented on src/main/java/com/devshop/devshop/service/DevshopService.java
> +    public List<Category> getCategoriesList() {
Dobra praktyka jest nazywanie metod w serwisie tak jak w repo, wiec skoro masz w repository nazwe metody `findAll()` to fajnie by bylo jakby w serwisie metoda tez byla `findAll()` :)

2019-09-08 07:19 UTC, CKochanski commented
Konflikty do rowiazania!

2019-09-08 08:22 UTC, StanislawGlegola commented on src/main/java/com/devshop/devshop/controller/AppController.java
> +    @GetMapping("/home")
done

2019-09-08 08:26 UTC, merged